version: "3.9"
services:
  master-api:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service

  user-service:
    build: ./user-service
    ports:
      - "4002:4002"

